name: Repository Privatization

on:
  push:
    branches:
      - main

jobs:
  privatize-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.0

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Privatize Repository
        run: python privatize_repo.py

      - name: Debug Access Token
        run: echo ${{ secrets.ACCESS_TOKEN }}


      - name: Privatize Repository
        run: |
          # Use the appropriate Git commands or Git library in your preferred programming language to privatize the repository.
          git config --global user.name "Tanmay-Somani"
          git config --global user.email "tanmaysomani2003@gmail.com"
          git init
          git remote add origin https://github.com/Tanmay-Somani/git-init.git
          git fetch
          git checkout main
          git update-ref -d refs/heads/main
          git checkout --orphan main
          git commit --allow-empty -m "Privatize repository"
          git push --force origin main
